-- ============================================================
-- BYG Rodamientos — Seed de datos
-- Ejecutar DESPUÉS del schema.sql
-- ============================================================

-- UUIDs fijos para categorías (consistentes entre entornos)
-- rodamientos: a1000000-0000-0000-0000-000000000001
-- retenes:     a2000000-0000-0000-0000-000000000002
-- transmision: a3000000-0000-0000-0000-000000000003
-- herramientas:a4000000-0000-0000-0000-000000000004
-- sellos:      a5000000-0000-0000-0000-000000000005
-- automotriz:  a6000000-0000-0000-0000-000000000006

-- ────────────────────────────────────────────────────────────
-- CATEGORÍAS
-- ────────────────────────────────────────────────────────────
insert into categorias (id, nombre, slug) values
  ('a1000000-0000-0000-0000-000000000001', 'Rodamientos Industriales', 'rodamientos'),
  ('a2000000-0000-0000-0000-000000000002', 'Retenes', 'retenes'),
  ('a3000000-0000-0000-0000-000000000003', 'Componentes de Transmisión', 'transmision'),
  ('a4000000-0000-0000-0000-000000000004', 'Herramientas', 'herramientas'),
  ('a5000000-0000-0000-0000-000000000005', 'Sellos Mecánicos', 'sellos'),
  ('a6000000-0000-0000-0000-000000000006', 'Línea Automotriz', 'automotriz')
on conflict (slug) do nothing;

-- ────────────────────────────────────────────────────────────
-- PRODUCTOS — RODAMIENTOS (10)
-- ────────────────────────────────────────────────────────────
insert into productos (nombre, slug, descripcion, descripcion_larga, categoria_id, subcategoria, stock, imagen_url, especificaciones, aplicaciones, caracteristicas, fabricante, activo) values

('Rodamiento Rígido de Bolas 6200 Series',
 'rodamiento-rigido-bolas-6200',
 'Rodamientos rígidos de bolas para aplicaciones generales de alta velocidad y baja fricción',
 'Los rodamientos rígidos de bolas son los más versátiles y ampliamente utilizados. Diseñados para soportar cargas radiales y axiales moderadas en ambas direcciones. Ideales para aplicaciones de alta velocidad con mínima fricción y bajo nivel de ruido. Disponibles en diversas configuraciones: abiertos, con protecciones metálicas (Z, ZZ) o con sellos de goma (RS, 2RS).',
 'a1000000-0000-0000-0000-000000000001',
 'rigidos-bolas',
 10,
 '/images/products/rodamientorigidodebolas (1).webp',
 '{"Tipo":"Rígido de bolas","Serie":"6200","Carga radial":"Alta","Carga axial":"Moderada","Velocidad":"Muy alta","Temperatura":"-30°C a +110°C","Material jaula":"Acero estampado o poliamida","Protección":"Abierto, Z, ZZ, RS, 2RS"}',
 ARRAY['Motores eléctricos','Bombas centrífugas','Ventiladores industriales','Reductores de velocidad','Electrodomésticos','Maquinaria textil'],
 ARRAY['Baja fricción y bajo nivel de ruido','Alta velocidad de funcionamiento','Mantenimiento mínimo','Diseño simple y robusto','Amplia disponibilidad de medidas','Excelente relación calidad-precio'],
 'NSK / SKF / FAG',
 true),

('Rodamiento de Bolas a Rótula',
 'rodamiento-bolas-rotula',
 'Rodamientos auto-alineantes para aplicaciones con desalineación del eje',
 'Los rodamientos de bolas a rótula tienen dos hileras de bolas que funcionan sobre una pista esférica común en el aro exterior, lo que les permite ser insensibles a las desalineaciones del eje respecto al soporte. Ideales para aplicaciones donde es difícil garantizar un perfecto alineamiento o donde existen deflexiones del eje.',
 'a1000000-0000-0000-0000-000000000001',
 'bolas-rotula',
 10,
 '/images/products/rodamiento-de-bolas-a-rotula (1).webp',
 '{"Tipo":"Bolas a rótula","Serie":"1200, 2200","Hileras":"Doble","Capacidad auto-alineante":"±3°","Carga radial":"Alta","Velocidad":"Media-alta","Temperatura":"-30°C a +120°C"}',
 ARRAY['Equipos mineros','Maquinaria agrícola','Transportadores','Molinos','Ventiladores de gran tamaño','Equipos de construcción'],
 ARRAY['Auto-alineante hasta ±3°','Soporta desalineación del eje','Alta capacidad de carga radial','Reducción de problemas de montaje','Vida útil prolongada en condiciones difíciles','Disponible con agujero cónico o cilíndrico'],
 'SKF / FAG / NSK',
 true),

('Rodamiento de Contacto Angular',
 'rodamiento-contacto-angular',
 'Rodamientos para altas cargas axiales combinadas con cargas radiales',
 'Los rodamientos de contacto angular tienen pistas en los aros interior y exterior desplazadas entre sí en la dirección del eje del rodamiento. Esto permite que soporten cargas combinadas (radiales y axiales simultáneamente). El ángulo de contacto determina la capacidad de carga: mayor ángulo = mayor capacidad axial.',
 'a1000000-0000-0000-0000-000000000001',
 'contacto-angular',
 10,
 '/images/products/contacto-angular (1).webp',
 '{"Tipo":"Contacto angular","Serie":"7200, 7300","Ángulo de contacto":"15°, 25°, 40°","Carga axial":"Muy alta","Carga radial":"Alta","Velocidad":"Alta","Configuración":"Simple, apareado","Temperatura":"-30°C a +120°C"}',
 ARRAY['Husillos de máquinas herramienta','Bombas de alta presión','Compresores','Cajas de engranajes','Maquinaria de precisión','Equipos dentales'],
 ARRAY['Alta capacidad de carga axial','Soporta cargas combinadas','Alta precisión de funcionamiento','Puede montarse en configuración apareada','Diferentes ángulos de contacto disponibles','Excelente para altas velocidades'],
 'FAG / NSK / SKF',
 true),

('Rodamiento de Rodillos Cilíndricos',
 'rodamiento-rodillos-cilindricos',
 'Rodamientos de alta capacidad de carga radial para aplicaciones pesadas',
 'Los rodamientos de rodillos cilíndricos tienen elementos rodantes cilíndricos que están en contacto lineal con las pistas. Esto les proporciona una alta capacidad de carga radial y permiten altas velocidades. Son separables, lo que facilita el montaje y desmontaje.',
 'a1000000-0000-0000-0000-000000000001',
 'rodillos-cilindricos',
 10,
 '/images/products/contacto-cilindrico (1).webp',
 '{"Tipo":"Rodillos cilíndricos","Serie":"NU, NJ, NUP, N","Carga radial":"Muy alta","Carga axial":"Limitada o nula","Velocidad":"Alta","Diseño":"Separable","Temperatura":"-40°C a +120°C"}',
 ARRAY['Motores de tracción','Reductores de velocidad pesados','Laminadores','Máquinas papeleras','Compresores grandes','Turbinas'],
 ARRAY['Muy alta capacidad de carga radial','Diseño separable facilita montaje','Alta rigidez','Baja fricción','Adecuado para altas velocidades','Disponible en diversas configuraciones'],
 'SKF / Timken / NSK',
 true),

('Rodamiento de Rodillos a Rótula',
 'rodamiento-rodillos-rotula',
 'Rodamientos de máxima carga para aplicaciones extremas con desalineación',
 'Los rodamientos de rodillos a rótula tienen dos hileras de rodillos simétricos que trabajan sobre una pista esférica común. Combinan una altísima capacidad de carga con la capacidad de compensar desalineaciones. Son la solución para las aplicaciones más exigentes de la industria pesada.',
 'a1000000-0000-0000-0000-000000000001',
 'rodillos-rotula',
 10,
 '/images/products/Rodamientos-Axiales-de-Rodillos-a-Rótula (1).webp',
 '{"Tipo":"Rodillos a rótula","Serie":"222, 223, 230, 231","Hileras":"Doble","Capacidad auto-alineante":"±3°","Carga radial":"Extremadamente alta","Velocidad":"Media","Temperatura":"-40°C a +120°C"}',
 ARRAY['Molinos de bolas','Trituradoras','Equipos de minería pesada','Laminadores de acero','Grúas y puentes grúa','Maquinaria de construcción pesada'],
 ARRAY['Capacidad de carga extremadamente alta','Auto-alineante hasta ±3°','Soporta cargas de choque','Diseño robusto para condiciones extremas','Larga vida útil en aplicaciones pesadas','Reduce costos de mantenimiento'],
 'SKF / FAG / Timken',
 true),

('Rodamiento Axial de Bolas',
 'rodamiento-axial-bolas',
 'Rodamientos para cargas axiales puras a velocidades moderadas',
 'Los rodamientos axiales de bolas están diseñados para soportar exclusivamente cargas axiales en una dirección. Constan de dos aros y una jaula con bolas. Son ideales para aplicaciones donde la carga principal es axial y la velocidad es moderada.',
 'a1000000-0000-0000-0000-000000000001',
 'axiales',
 10,
 '/images/products/Axial a bola (2).webp',
 '{"Tipo":"Axial de bolas","Serie":"511, 512, 513","Dirección de carga":"Unidireccional","Carga axial":"Alta","Carga radial":"No admite","Velocidad":"Media","Temperatura":"-20°C a +100°C"}',
 ARRAY['Taladros y fresadoras','Grúas (giro de pluma)','Mesas giratorias','Cajas de engranajes','Sistemas de elevación','Equipos de posicionamiento'],
 ARRAY['Soporta cargas axiales elevadas','Diseño compacto','Bajo consumo de espacio axial','Fácil montaje','Económico','Varias configuraciones disponibles'],
 'FAG / INA / NSK',
 true),

('Rodamiento de Agujas',
 'rodamiento-agujas',
 'Rodamientos compactos de alta capacidad para espacios reducidos',
 'Los rodamientos de agujas utilizan elementos rodantes cilíndricos muy finos y largos (agujas). Esta configuración permite una alta capacidad de carga en un diseño muy compacto con mínima sección radial. Ideales para aplicaciones donde el espacio es limitado pero se requiere alta capacidad de carga.',
 'a1000000-0000-0000-0000-000000000001',
 'agujas',
 10,
 '/images/products/agujas1.webp',
 '{"Tipo":"Agujas","Diámetro agujas":"1.5-5 mm","Relación L/D":"2.5 a 10","Carga radial":"Muy alta para su tamaño","Sección radial":"Mínima","Velocidad":"Media-alta","Temperatura":"-30°C a +120°C"}',
 ARRAY['Transmisiones automotrices','Bielas de motores','Ejes de levas','Articulaciones universales','Bombas hidráulicas','Máquinas textiles'],
 ARRAY['Sección radial mínima','Alta capacidad de carga radial','Ahorro de espacio y peso','Bajo coeficiente de fricción','Alta rigidez','Diversas configuraciones disponibles'],
 'INA / NSK / Koyo',
 true),

('Rodamiento de Cubo de Rueda',
 'rodamiento-cubos-rueda',
 'Rodamientos especiales para aplicaciones automotrices',
 'Los rodamientos de cubo de rueda son unidades completas diseñadas específicamente para aplicaciones automotrices. Integran rodamientos de bolas de contacto angular o rodillos cónicos en una configuración sellada y pre-lubricada. Ofrecen máxima confiabilidad y facilidad de montaje.',
 'a1000000-0000-0000-0000-000000000001',
 'rigidos-bolas',
 10,
 '/images/products/cubo de rueda.webp',
 '{"Tipo":"Cubo de rueda (HUB)","Generación":"1, 2 o 3","Sellado":"Integral","Lubricación":"De por vida","Carga combinada":"Radial + axial","Montaje":"Rápido y sencillo"}',
 ARRAY['Automóviles ligeros','Camionetas','Vehículos comerciales ligeros','SUVs','Aplicaciones automotrices en general'],
 ARRAY['Pre-lubricado de por vida','Sellado integral','Montaje rápido y sencillo','Alta confiabilidad','Reducción de peso','Compatible con sistemas ABS'],
 'SKF / Timken / NSK',
 true),

('Rodamiento de Rodillos Cónicos',
 'rodamiento-rodillos-conicos',
 'Rodamientos para cargas combinadas radiales y axiales elevadas',
 'Los rodamientos de rodillos cónicos tienen rodillos en forma de tronco de cono que trabajan sobre pistas cónicas. Son separables y pueden soportar cargas combinadas radiales y axiales. Se montan normalmente en pares enfrentados o en tándem, siendo esenciales en aplicaciones automotrices e industriales pesadas.',
 'a1000000-0000-0000-0000-000000000001',
 'rodillos-cilindricos',
 10,
 '/images/products/rodillo conico.webp',
 '{"Tipo":"Rodillos cónicos","Serie":"302, 303, 320, 322","Carga radial":"Muy alta","Carga axial":"Alta","Diseño":"Separable","Montaje":"En pares o individual","Temperatura":"-40°C a +120°C"}',
 ARRAY['Cajas de cambios automotrices','Diferenciales de vehículos','Rodillos de laminadores','Reductores de velocidad','Ejes ferroviarios','Maquinaria de construcción'],
 ARRAY['Soporta cargas combinadas muy altas','Diseño separable facilita montaje','Ajustable para eliminar juego','Alta rigidez','Larga vida útil','Amplia gama de tamaños'],
 'Timken / SKF / Koyo',
 true),

('Rodamiento Híbrido Cerámico',
 'rodamiento-ceramic-hibrido',
 'Rodamientos de alta performance con bolas cerámicas',
 'Los rodamientos híbridos combinan aros de acero con bolas de cerámica (nitruro de silicio). Ofrecen ventajas significativas en aplicaciones de alta velocidad, ambientes corrosivos o donde se requiere mínima lubricación. La cerámica es más dura, ligera y resistente que el acero.',
 'a1000000-0000-0000-0000-000000000001',
 'rigidos-bolas',
 10,
 '/images/products/hibrido ceramico.webp',
 '{"Tipo":"Híbrido cerámico","Material bolas":"Nitruro de silicio (Si3N4)","Material aros":"Acero cromado","Velocidad":"Extremadamente alta","Temperatura":"-60°C a +150°C","Resistencia química":"Excelente"}',
 ARRAY['Husillos de alta velocidad','Bombas químicas','Turbinas','Equipos médicos','Industria alimentaria','Ambientes corrosivos'],
 ARRAY['Velocidades extremadamente altas','Menor fricción y calentamiento','Resistencia a corrosión','No magnético','Mayor vida útil','Menor necesidad de lubricación'],
 'SKF / NSK / GMN',
 true);

-- ────────────────────────────────────────────────────────────
-- PRODUCTOS — RETENES (9)
-- ────────────────────────────────────────────────────────────
insert into productos (nombre, slug, descripcion, descripcion_larga, categoria_id, subcategoria, stock, imagen_url, especificaciones, aplicaciones, caracteristicas, activo) values

('Retén de Nitrilo Clásico',
 'reten-nitrilo-clasico',
 'Retén estándar de nitrilo (NBR) para aplicaciones industriales generales',
 'El retén de nitrilo clásico es el más utilizado en la industria por su excelente relación costo-beneficio. Fabricado en caucho nitrilo (NBR), ofrece buena resistencia a aceites minerales, grasas, combustibles y agua. Su diseño con labio simple y carcasa metálica garantiza un sellado confiable en ejes rotativos. Disponible en todas las medidas estándar.',
 'a2000000-0000-0000-0000-000000000002',
 'nitrilo-clasico',
 10,
 '/images/products/nitrilo clasico.webp',
 '{"Material":"Nitrilo (NBR)","Temperatura":"-40°C a +100°C","Resistencia":"Aceites minerales, grasas, combustibles","Dureza":"70 Shore A","Perfil":"Labio simple con carcasa metálica","Velocidad periférica":"Hasta 12 m/s","Presión":"Hasta 0.05 MPa"}',
 ARRAY['Cajas reductoras','Motores eléctricos','Bombas hidráulicas','Maquinaria industrial general','Transmisiones mecánicas','Equipos agrícolas'],
 ARRAY['Excelente resistencia a aceites minerales','Buena resistencia mecánica al desgaste','Económico y de amplia disponibilidad','Fácil montaje y reemplazo','Carcasa metálica para mayor rigidez','Todas las medidas estándar en stock'],
 true),

('Retén de Nitrilo con Resorte',
 'reten-nitrilo-resorte',
 'Retén de nitrilo con resorte de acero inoxidable para mayor presión de sellado',
 'El retén de nitrilo con resorte incorpora un resorte helicoidal de acero inoxidable que mantiene una presión constante del labio sobre el eje, compensando el desgaste natural y las variaciones térmicas. Esto garantiza un sellado superior y una vida útil más prolongada que el retén clásico.',
 'a2000000-0000-0000-0000-000000000002',
 'nitrilo-resorte',
 10,
 '/images/products/RETENES DE NITRILO CON RESORTE.webp',
 '{"Material":"Nitrilo (NBR) + resorte AISI 304","Temperatura":"-40°C a +100°C","Resistencia":"Aceites minerales, grasas, combustibles","Dureza":"70 Shore A","Perfil":"Labio con resorte helicoidal","Velocidad periférica":"Hasta 15 m/s","Presión":"Hasta 0.07 MPa"}',
 ARRAY['Reductores de velocidad','Motores eléctricos de alta exigencia','Bombas centrífugas','Compresores','Equipos de minería','Maquinaria de producción continua'],
 ARRAY['Resorte compensa desgaste del labio','Mayor vida útil que el retén clásico','Presión de sellado constante','Mejor rendimiento a altas velocidades','Compensación de variaciones térmicas','Sellado confiable en condiciones exigentes'],
 true),

('Retén de Nitrilo con Rosca',
 'reten-nitrilo-rosca',
 'Retén de nitrilo con rosca helicoidal para efecto de bombeo y máximo sellado',
 'El retén de nitrilo con rosca incorpora una hélice en el labio que genera un efecto de bombeo durante la rotación del eje, devolviendo el fluido al interior del equipo. Proporciona un sellado superior, especialmente en aplicaciones con presión diferencial o donde se requiere evitar cualquier fuga mínima.',
 'a2000000-0000-0000-0000-000000000002',
 'nitrilo-rosca',
 10,
 '/images/products/reten de nitrilo con rosca.webp',
 '{"Material":"Nitrilo (NBR)","Temperatura":"-40°C a +100°C","Resistencia":"Aceites minerales, grasas, polvo","Dureza":"70 Shore A","Perfil":"Labio con rosca helicoidal","Velocidad periférica":"Hasta 14 m/s","Efecto":"Bombeo de retorno"}',
 ARRAY['Equipos en ambientes polvorientos','Maquinaria de construcción','Equipos agrícolas','Transmisiones expuestas','Motores industriales','Equipos de minería'],
 ARRAY['Efecto de bombeo devuelve fluido al interior','Sellado superior contra contaminación','Protección contra ingreso de polvo','Menor fuga que retenes convencionales','Ideal para ambientes agresivos','Disponible para sentido horario y antihorario'],
 true),

('Retén de Nitrilo Bidireccional',
 'reten-nitrilo-bidireccional',
 'Retén de nitrilo con doble capacidad de sellado para ejes con rotación en ambos sentidos',
 'El retén bidireccional de nitrilo está diseñado con un perfil de labio simétrico que permite sellar eficazmente independientemente del sentido de rotación del eje. A diferencia de los retenes convencionales que sellan en una sola dirección, el bidireccional mantiene su rendimiento sin importar si el eje gira en sentido horario o antihorario.',
 'a2000000-0000-0000-0000-000000000002',
 'nitrilo-bidireccional',
 10,
 '/images/products/nitrilo bidireccional.webp',
 '{"Material":"Nitrilo (NBR)","Temperatura":"-40°C a +100°C","Resistencia":"Aceites minerales, grasas","Dureza":"70 Shore A","Perfil":"Labio simétrico bidireccional","Velocidad periférica":"Hasta 12 m/s","Dirección":"Ambos sentidos de rotación"}',
 ARRAY['Motores reversibles','Winches y malacates','Equipos con cambio de sentido de giro','Transmisiones reversibles','Maquinaria con ciclos alternados','Equipos hidráulicos bidireccionales'],
 ARRAY['Sella en ambos sentidos de rotación','Perfil de labio simétrico','No requiere orientación de montaje','Ideal para ejes reversibles','Reduce errores de instalación','Misma performance en ambas direcciones'],
 true),

('Retén Doble Labio',
 'reten-doble-labio',
 'Retén con doble labio de sellado para máxima protección contra contaminantes',
 'El retén doble labio cuenta con un labio primario de sellado del fluido y un labio secundario guardapolvo que impide el ingreso de partículas y contaminantes externos. Esta doble barrera es esencial en ambientes extremadamente sucios o polvorientos donde un solo labio no garantiza protección suficiente.',
 'a2000000-0000-0000-0000-000000000002',
 'doble-labio',
 10,
 '/images/products/doble labio.webp',
 '{"Material":"Nitrilo (NBR) / Vitón (FKM)","Temperatura":"-40°C a +100°C (NBR) / -20°C a +200°C (FKM)","Resistencia":"Aceites, grasas, polvo, barro","Perfil":"Doble labio (sellado + guardapolvo)","Velocidad periférica":"Hasta 10 m/s","Protección":"Doble barrera contra contaminación"}',
 ARRAY['Maquinaria de construcción pesada','Equipos mineros','Maquinaria agrícola','Equipos forestales','Cementeras y canteras','Cualquier ambiente con alta contaminación'],
 ARRAY['Doble barrera de sellado','Labio guardapolvo contra contaminantes','Cámara entre labios para grasa','Protección superior en ambientes sucios','Mayor vida útil del rodamiento protegido','Disponible en NBR y Vitón'],
 true),

('Retén de Vitón (FKM)',
 'reten-viton-fkm',
 'Retén de alto rendimiento para altas temperaturas y fluidos agresivos',
 'Los retenes de Vitón (FKM) ofrecen excelente resistencia química y térmica, siendo la opción premium para las aplicaciones más exigentes. Soportan temperaturas de hasta +200°C y son resistentes a aceites sintéticos, combustibles, solventes y fluidos hidráulicos agresivos.',
 'a2000000-0000-0000-0000-000000000002',
 'viton',
 10,
 '/images/products/reten viton.webp',
 '{"Material":"Vitón (FKM / Fluoroelastómero)","Temperatura":"-20°C a +200°C","Resistencia":"Aceites sintéticos, solventes, combustibles, ácidos","Dureza":"75 Shore A","Velocidad periférica":"Hasta 15 m/s","Presión":"Hasta 0.05 MPa"}',
 ARRAY['Industria petroquímica','Motores de alta temperatura','Compresores industriales','Bombas químicas','Equipos con aceites sintéticos','Industria alimentaria (alta temperatura)'],
 ARRAY['Resistencia a temperaturas hasta +200°C','Excelente resistencia química','Larga vida útil en condiciones extremas','Baja permeabilidad a gases','Resistente al ozono y UV','Material premium para aplicaciones críticas'],
 true),

('Retén de Silicona',
 'reten-silicona',
 'Retén de silicona para industria alimentaria, farmacéutica y temperaturas extremas',
 'Los retenes de silicona (VMQ) son ideales para contacto con alimentos y aplicaciones de temperatura extrema. Su amplio rango térmico (-60°C a +200°C) y compatibilidad con normativas sanitarias FDA los hacen imprescindibles en la industria alimentaria y farmacéutica.',
 'a2000000-0000-0000-0000-000000000002',
 'silicona',
 10,
 '/images/products/reten de silicona.webp',
 '{"Material":"Silicona (VMQ)","Temperatura":"-60°C a +200°C","Certificación":"FDA aprobado","Dureza":"60-80 Shore A","Resistencia":"Agua, aire, ozono, UV","Velocidad periférica":"Hasta 8 m/s"}',
 ARRAY['Industria alimentaria','Equipos farmacéuticos','Hornos industriales','Equipos médicos','Industria láctea','Procesamiento de bebidas'],
 ARRAY['Apto para contacto alimentario (FDA)','Rango térmico extremo (-60°C a +200°C)','No tóxico, inodoro e insípido','Resistente al ozono y UV','Alta flexibilidad a bajas temperaturas','Fisiológicamente inerte'],
 true),

('Retén de Poliacrílico',
 'reten-poliacrilico',
 'Retén de caucho poliacrílico (ACM) para aceites a alta temperatura',
 'Los retenes de poliacrílico (ACM) están diseñados específicamente para trabajar con aceites lubricantes a temperaturas superiores a las que soporta el nitrilo. Ofrecen excelente resistencia al aceite caliente, a los aditivos EP y a los fluidos de transmisión automática (ATF).',
 'a2000000-0000-0000-0000-000000000002',
 'poliacrilico',
 10,
 null,
 '{"Material":"Poliacrílico (ACM)","Temperatura":"-25°C a +150°C","Resistencia":"Aceites calientes, ATF, aditivos EP","Dureza":"70-80 Shore A","Velocidad periférica":"Hasta 15 m/s","Norma":"OEM automotriz"}',
 ARRAY['Cigüeñales de motores','Cárter de aceite','Transmisiones automáticas','Diferenciales','Equipos con aceite a alta temperatura','Aplicaciones OEM automotriz'],
 ARRAY['Superior al nitrilo en aceites calientes','Excelente resistencia a aditivos EP','Estándar OEM automotriz','Buena resistencia al envejecimiento','Compatible con fluidos ATF','Sellado confiable en alta temperatura'],
 true),

('O-Rings',
 'orings',
 'Sellos tóricos O-Ring en diversos materiales y medidas para sellado estático y dinámico',
 'Los O-Rings son sellos de sección circular utilizados para sellado estático y dinámico en una gran variedad de aplicaciones. Disponibles en nitrilo (NBR), vitón (FKM), silicona (VMQ), EPDM y PTFE, cubren prácticamente cualquier requerimiento de temperatura, presión y compatibilidad química.',
 'a2000000-0000-0000-0000-000000000002',
 'orings',
 10,
 '/images/products/ORINGS.webp',
 '{"Materiales":"NBR, FKM, VMQ, EPDM, PTFE","Temperatura":"-60°C a +250°C (según material)","Presión":"Hasta 40 MPa (con anillos anti-extrusión)","Normas":"AS568, DIN 3771, ISO 3601","Secciones":"De 1 mm a 10 mm","Aplicación":"Estática y dinámica"}',
 ARRAY['Cilindros hidráulicos','Conexiones neumáticas','Válvulas industriales','Bombas','Equipos de refrigeración','Instrumentación y control'],
 ARRAY['Amplia variedad de materiales','Medidas estándar y especiales','Sellado estático y dinámico','Normas internacionales AS568 / DIN / ISO','Económicos y de fácil instalación','Stock de medidas más frecuentes'],
 true);

-- ────────────────────────────────────────────────────────────
-- PRODUCTOS — TRANSMISIÓN (5)
-- ────────────────────────────────────────────────────────────
insert into productos (nombre, slug, descripcion, descripcion_larga, categoria_id, subcategoria, stock, imagen_url, especificaciones, aplicaciones, caracteristicas, fabricante, activo) values

('Manguitos de Fijación Serie H',
 'manguito-fijacion-h',
 'Manguitos de fijación cónicos para montaje de rodamientos sobre ejes lisos. Fijación segura sin necesidad de escalones en el eje.',
 'Los manguitos de fijación serie H son elementos cónicos diseñados para montar rodamientos con agujero cónico sobre ejes cilíndricos lisos. Permiten un posicionamiento axial libre del rodamiento sobre el eje, eliminando la necesidad de escalones o roscas. Fabricados en acero de alta resistencia con tuerca ranurada y arandela de seguridad incluidas.',
 'a3000000-0000-0000-0000-000000000003',
 'manguitos',
 10,
 '/images/products/manguito de fijacion.webp',
 '{"Tipo":"Manguito de fijación cónico","Serie":"H200 / H300 / H2300 / H3100","Material":"Acero al carbono","Conicidad":"1:12","Acabado superficial":"Fosfatado","Incluye":"Tuerca ranurada + arandela de seguridad","Rango de diámetros":"15 mm a 200 mm","Norma":"DIN 5415 / ISO 2982"}',
 ARRAY['Ejes de transmisión industrial','Ventiladores y extractores','Transportadores de banda','Maquinaria agrícola','Reductores de velocidad','Bombas centrífugas'],
 ARRAY['Montaje sobre ejes lisos sin escalones','Posicionamiento axial libre del rodamiento','Tuerca ranurada y arandela de seguridad incluidas','Fácil montaje y desmontaje','Alta capacidad de sujeción','Disponible en múltiples series y medidas'],
 'SKF / NTN / FAG',
 true),

('Acoples Flexibles de Mordaza',
 'acoples-flexibles',
 'Acoples flexibles tipo mordaza para conexión de ejes. Compensan desalineaciones angulares, radiales y axiales.',
 'Los acoples flexibles de mordaza son elementos de transmisión diseñados para conectar dos ejes y transmitir par de torsión, compensando simultáneamente desalineaciones angulares, radiales y axiales. Compuestos por dos cubos de aluminio o acero y un inserto elastomérico intercambiable en distintas durezas.',
 'a3000000-0000-0000-0000-000000000003',
 'acoples',
 10,
 '/images/products/acoples flexibles.webp',
 '{"Tipo":"Acople flexible de mordaza (jaw coupling)","Material cubos":"Aluminio / Acero / Fundición","Material inserto":"Poliuretano (elastómero)","Dureza inserto":"Shore 92A (estándar) / 80A / 98A","Par máximo":"Hasta 2.500 Nm según tamaño","RPM máximas":"Hasta 19.000 RPM","Temperatura de trabajo":"-40°C a +100°C","Desalineación angular":"Hasta 1°","Desalineación radial":"Hasta 0,15 mm"}',
 ARRAY['Bombas centrífugas y de engranajes','Compresores de aire','Motores eléctricos','Generadores','Máquinas herramienta','Sistemas de ventilación industrial'],
 ARRAY['Compensación de desalineaciones múltiples','Inserto elastomérico intercambiable','Montaje y desmontaje sin mover equipos','Libre de mantenimiento y lubricación','Amortiguación de vibraciones y golpes','Amplia gama de tamaños disponibles'],
 'Lovejoy / Martin / KTR',
 true),

('Acoples Industriales Rígidos',
 'acoples-industriales-rigidos',
 'Acoples rígidos de alta precisión para transmisión directa de par. Máxima eficiencia en ejes perfectamente alineados.',
 'Los acoples industriales rígidos están diseñados para aplicaciones donde los ejes se encuentran perfectamente alineados y se requiere una transmisión directa del par sin pérdidas. Fabricados en acero o fundición de alta resistencia, ofrecen máxima rigidez torsional y capacidad de par.',
 'a3000000-0000-0000-0000-000000000003',
 'acoples',
 10,
 '/images/products/acoples industriales.webp',
 '{"Tipo":"Acople rígido (brida / manguito partido / abrazadera)","Material":"Acero inoxidable / Acero al carbono / Aluminio","Par máximo":"Hasta 10.000 Nm según modelo","RPM máximas":"Hasta 10.000 RPM","Precisión concentricidad":"< 0,025 mm TIR","Temperatura de trabajo":"-30°C a +120°C","Acabado":"Mecanizado de precisión, anodizado (aluminio)","Fijación":"Tornillos de alta resistencia / prisioneros"}',
 ARRAY['Máquinas herramienta CNC','Servomotores y actuadores','Sistemas de posicionamiento','Equipos de ensayo y medición','Transmisiones de alta precisión','Automatización industrial'],
 ARRAY['Transmisión directa sin pérdidas','Máxima rigidez torsional','Alta precisión de concentricidad','Diseño compacto y robusto','Sin juego angular (zero backlash)','Fácil instalación con tornillos de fijación'],
 'Ruland / Rexnord / Stafford',
 true),

('Poleas de Transmisión',
 'poleas-transmision',
 'Poleas de transmisión en V, sincrónicas y planas para sistemas de correas industriales.',
 'Amplia gama de poleas de transmisión para sistemas de correas industriales. Incluye poleas en V (perfil A, B, C, SPZ, SPA, SPB), poleas sincrónicas (dentadas) para correas de distribución, y poleas planas. Fabricadas en fundición gris, acero o aluminio con mecanizado de precisión.',
 'a3000000-0000-0000-0000-000000000003',
 'poleas',
 10,
 '/images/products/poleas.webp',
 '{"Tipos":"Polea en V / Sincrónica / Plana","Perfiles en V":"A, B, C, D, SPZ, SPA, SPB, SPC","Perfiles sincrónicas":"HTD (3M, 5M, 8M, 14M), T5, T10, AT5, AT10","Material":"Fundición gris GG25 / Acero / Aluminio","Número de canales":"1 a 10 canales","Fijación":"Buje taper lock / Agujero con chavetero","Balanceo":"Grado G6.3 según ISO 1940","Acabado":"Fosfatado / Pintado / Mecanizado"}',
 ARRAY['Compresores industriales','Ventiladores y extractores','Transportadores de banda','Maquinaria textil','Trituradoras y molinos','Sistemas de bombeo'],
 ARRAY['Amplia variedad de perfiles y tamaños','Compatibles con buje taper lock','Balanceo de precisión para baja vibración','Fundición de alta calidad GG25','Múltiples canales disponibles','Stock de medidas más comunes'],
 'Optibelt / Gates / Martin',
 true),

('Correas de Transmisión',
 'correas-transmision',
 'Correas de transmisión en V, sincrónicas y multi-V para aplicaciones industriales y automotrices.',
 'Línea completa de correas de transmisión para aplicaciones industriales y automotrices. Incluye correas trapeciales clásicas, correas estrechas de alto rendimiento, correas sincrónicas y correas multi-V. Fabricadas con compuestos de caucho de alta tecnología reforzados con cordones de poliéster, aramida o fibra de vidrio.',
 'a3000000-0000-0000-0000-000000000003',
 'correas',
 10,
 '/images/products/correas.webp',
 '{"Tipos":"Trapecial clásica / Estrecha / Sincrónica / Multi-V","Perfiles clásicos":"A (13x8mm), B (17x11mm), C (22x14mm)","Perfiles estrechos":"SPZ, SPA, SPB, SPC","Perfiles sincrónicas":"HTD 3M, 5M, 8M, 14M","Material base":"Caucho EPDM / Caucho cloropreno","Refuerzo":"Cordones de poliéster / Aramida / Fibra de vidrio","Temperatura de trabajo":"-30°C a +80°C (estándar)","Velocidad máxima":"Hasta 50 m/s según tipo"}',
 ARRAY['Motores eléctricos industriales','Compresores de aire y refrigeración','Bombas industriales','Sistemas de climatización HVAC','Maquinaria agrícola','Equipos de minería y canteras'],
 ARRAY['Alta resistencia a la fatiga y elongación','Funcionamiento silencioso y sin vibraciones','Resistentes a aceites, calor y ozono','Transmisión de potencia eficiente (hasta 98%)','Larga vida útil con bajo mantenimiento','Amplio stock de medidas estándar'],
 'Optibelt / Gates / Continental',
 true);

-- ────────────────────────────────────────────────────────────
-- PRODUCTOS — HERRAMIENTAS (4)
-- ────────────────────────────────────────────────────────────
insert into productos (nombre, slug, descripcion, descripcion_larga, categoria_id, subcategoria, stock, imagen_url, especificaciones, aplicaciones, caracteristicas, fabricante, activo) values

('Extractor Hidráulico de Tres Garras',
 'extractor-hidraulico-tres-garras',
 'Extractor hidráulico de tres garras autocentrante para desmontaje de rodamientos, engranajes y poleas.',
 'Extractor hidráulico de tres garras con sistema autocentrante para desmontaje seguro y eficiente de rodamientos, engranajes, poleas y bujes. El accionamiento hidráulico permite aplicar fuerzas de extracción elevadas y controladas, reduciendo el riesgo de daño a componentes. Las garras reversibles permiten trabajar en modo interior y exterior.',
 'a4000000-0000-0000-0000-000000000004',
 'extractores',
 10,
 '/images/products/extractor hidráulico de tres garras.webp',
 '{"Tipo":"Extractor hidráulico de 3 garras autocentrante","Fuerza de extracción":"5 a 50 toneladas según modelo","Apertura máxima":"50 mm a 380 mm según modelo","Profundidad de agarre":"80 mm a 250 mm","Material garras":"Acero aleado Cr-Mo tratado térmicamente","Presión hidráulica":"Hasta 700 bar","Garras reversibles":"Sí (modo interior y exterior)","Norma":"DIN 5234"}',
 ARRAY['Desmontaje de rodamientos','Extracción de engranajes','Remoción de poleas y bujes','Mantenimiento de motores eléctricos','Talleres de reparación industrial','Mantenimiento preventivo y correctivo'],
 ARRAY['Accionamiento hidráulico para fuerza controlada','Sistema autocentrante de precisión','Garras reversibles interior/exterior','Acero aleado Cr-Mo de alta resistencia','Protección contra sobrecarga','Múltiples tamaños disponibles'],
 'SKF / Enerpac / Betex',
 true),

('Kit de Extractores Internos de Rodamientos',
 'kit-extractores-internos',
 'Kit completo de extractores internos para desmontaje de rodamientos desde el anillo interior cuando el acceso exterior no es posible.',
 'Kit profesional de extractores internos diseñado para el desmontaje de rodamientos desde el anillo interior, especialmente útil cuando no hay acceso al anillo exterior (rodamientos montados en alojamientos ciegos). Incluye múltiples segmentos de agarre intercambiables que se expanden dentro del anillo interior del rodamiento.',
 'a4000000-0000-0000-0000-000000000004',
 'extractores',
 10,
 '/images/products/kit de extractores internos de rodamientos.webp',
 '{"Tipo":"Kit de extractores internos (blind bearing puller)","Rango de diámetros":"10 mm a 100 mm (según kit)","Cantidad de segmentos":"8 a 15 segmentos intercambiables","Material":"Acero al cromo-vanadio","Tipo de agarre":"Expansión interna por segmentos","Incluye":"Segmentos, husillo, contrapeso y maletín","Fuerza de extracción":"Hasta 10 toneladas","Acabado":"Cromado y pulido"}',
 ARRAY['Rodamientos en alojamientos ciegos','Rodamientos sin acceso al anillo exterior','Mantenimiento de cajas reductoras','Reparación de bombas industriales','Talleres mecánicos especializados','Mantenimiento de maquinaria pesada'],
 ARRAY['Extracción desde el anillo interior','Múltiples segmentos intercambiables','No daña el eje ni el alojamiento','Agarre firme y uniforme','Incluye maletín organizador','Cubre amplia gama de diámetros'],
 'SKF / Kukko / Gedore',
 true),

('Calentador de Rodamientos por Inducción',
 'calentador-induccion-rodamientos',
 'Calentador por inducción electromagnética para montaje de rodamientos, anillos y bujes. Calentamiento rápido, uniforme y controlado.',
 'Calentador de rodamientos por inducción electromagnética para montaje profesional de rodamientos, anillos interiores, bujes y engranajes sobre ejes. El calentamiento por inducción es el método recomendado por los principales fabricantes de rodamientos ya que garantiza un calentamiento rápido, uniforme y controlado sin contacto directo con llama.',
 'a4000000-0000-0000-0000-000000000004',
 'calentadores',
 10,
 '/images/products/calentador de rodamientos por inducción.webp',
 '{"Tipo":"Calentador por inducción electromagnética","Potencia":"3.6 kW / 8 kW / 12 kW según modelo","Peso máximo pieza":"10 kg a 150 kg según modelo","Diámetro máximo pieza":"Hasta 480 mm (interior)","Temperatura máxima":"250°C (ajustable)","Tiempo calentamiento":"30 seg a 10 min según pieza","Alimentación":"220V / 380V monofásico/trifásico","Desmagnetización":"Automática integrada","Control":"Digital con sensor de temperatura"}',
 ARRAY['Montaje de rodamientos sobre ejes','Calentamiento de anillos interiores','Montaje de bujes y casquillos','Montaje de engranajes con interferencia','Mantenimiento industrial programado','Talleres de reparación de motores'],
 ARRAY['Calentamiento rápido y uniforme por inducción','Control digital de temperatura con sensor','Desmagnetización automática de la pieza','Sin llama ni contacto directo','Protección contra sobrecalentamiento','Método recomendado por SKF, FAG y NSK'],
 'SKF / Betex / Bega',
 true),

('Grasa para Rodamientos Industrial',
 'grasa-rodamientos-industrial',
 'Grasa de litio de alto rendimiento para lubricación de rodamientos industriales. Excelente resistencia al agua, temperatura y carga.',
 'Grasa de alto rendimiento a base de jabón de litio/litio complejo formulada específicamente para la lubricación de rodamientos industriales. Ofrece excelente protección contra el desgaste, la corrosión y la oxidación. Su consistencia NLGI 2 la hace ideal para la mayoría de aplicaciones con rodamientos.',
 'a4000000-0000-0000-0000-000000000004',
 'lubricacion',
 10,
 '/images/products/grasa para rodamientos 1.webp',
 '{"Tipo":"Grasa de litio complejo","Grado NLGI":"2","Aceite base":"Aceite mineral de alta calidad","Viscosidad aceite base":"100 cSt a 40°C","Rango de temperatura":"-30°C a +150°C","Punto de goteo":"> 250°C","Resistencia al agua":"Excelente (DIN 51807: 0-90)","Color":"Marrón claro / Azul según marca","Presentaciones":"Cartucho 400g / Balde 5kg / Tambor 18kg / 180kg"}',
 ARRAY['Rodamientos de bolas y rodillos','Motores eléctricos','Bombas y ventiladores','Transportadores industriales','Maquinaria en general','Sistemas de lubricación centralizada'],
 ARRAY['Excelente protección antidesgaste','Alta resistencia al lavado por agua','Amplio rango de temperaturas de trabajo','Compatible con lubricación centralizada','Larga vida útil de relubricación','Múltiples presentaciones disponibles'],
 'SKF / Shell / Mobil',
 true);

-- ────────────────────────────────────────────────────────────
-- PRODUCTOS — AUTOMOTRIZ (4)
-- ────────────────────────────────────────────────────────────
insert into productos (nombre, slug, descripcion, descripcion_larga, categoria_id, subcategoria, stock, imagen_url, especificaciones, aplicaciones, caracteristicas, fabricante, activo) values

('Kit de Distribución',
 'kit-distribucion-automotriz',
 'Kits de distribución completos para vehículos nacionales e importados',
 'Kits de distribución completos que incluyen correa dentada, tensores y rodamientos auxiliares. Garantizan la correcta sincronización del motor, evitando daños graves por rotura o desgaste. Disponibles para una amplia variedad de marcas y modelos de vehículos nacionales e importados.',
 'a6000000-0000-0000-0000-000000000006',
 'distribucion',
 10,
 '/images/products/Kitdedistribucion.webp',
 '{"Tipo":"Kit de distribución completo","Incluye":"Correa dentada, tensor, rodillos guía","Aplicación":"Motores nafteros y diésel","Intervalo de cambio":"Según fabricante (60.000 - 120.000 km)","Marcas disponibles":"Gates, Dayco, SKF, Continental"}',
 ARRAY['Vehículos particulares','Utilitarios','Camionetas','Vehículos comerciales livianos'],
 ARRAY['Kit completo con todos los componentes necesarios','Correas de alta resistencia al desgaste','Tensores con rodamientos de precisión','Compatibilidad garantizada con el vehículo','Marcas de primera línea'],
 'Gates / Dayco / SKF',
 true),

('Bomba de Agua',
 'bomba-de-agua-automotriz',
 'Bombas de agua para el sistema de refrigeración del motor',
 'Bombas de agua para el circuito de refrigeración del motor. Aseguran la correcta circulación del refrigerante para mantener la temperatura óptima de funcionamiento. Fabricadas con materiales de alta durabilidad y sellos mecánicos de precisión para evitar pérdidas. Disponibles para múltiples marcas y modelos.',
 'a6000000-0000-0000-0000-000000000006',
 'bombas-agua',
 10,
 '/images/products/bomba de agua.webp',
 '{"Tipo":"Bomba de agua mecánica","Función":"Circulación de refrigerante","Material cuerpo":"Aluminio fundido","Material impulsor":"Fundición / Plástico reforzado","Sello":"Sello mecánico cerámico","Marcas disponibles":"Dolz, SKF, Graf, URO"}',
 ARRAY['Vehículos particulares','Utilitarios y camionetas','Vehículos comerciales','Motores nafteros y diésel'],
 ARRAY['Sello mecánico de alta durabilidad','Impulsor balanceado dinámicamente','Resistencia a altas temperaturas','Caudal óptimo para cada motorización','Instalación directa sin modificaciones'],
 'Dolz / SKF / Graf',
 true),

('Kit Poli V',
 'kit-poli-v-automotriz',
 'Kits de correa poli V con tensores para accesorios del motor',
 'Kits completos de correa poli V (correa de accesorios) que incluyen correa, tensor automático y rodillos guía. La correa poli V acciona los accesorios del motor: alternador, compresor de aire acondicionado, bomba de dirección hidráulica y otros componentes.',
 'a6000000-0000-0000-0000-000000000006',
 'kit-poli-v',
 10,
 '/images/products/kit poli v.webp',
 '{"Tipo":"Kit correa poli V completo","Incluye":"Correa poli V, tensor automático, rodillos guía","Material correa":"EPDM de alta resistencia","Perfil":"Micro V / Poli V","Marcas disponibles":"Gates, Dayco, Continental"}',
 ARRAY['Accionamiento de alternador','Compresor de aire acondicionado','Bomba de dirección hidráulica','Bomba de agua (en algunos motores)'],
 ARRAY['Correa EPDM de larga vida útil','Tensor automático para tensión constante','Kit completo para reemplazo integral','Reducción de ruidos y vibraciones','Compatibilidad OEM garantizada'],
 'Gates / Dayco / Continental',
 true),

('Cubo de Rueda',
 'cubo-de-rueda-automotriz',
 'Cubos de rueda y rodamientos para todo tipo de vehículos',
 'Cubos de rueda (wheel hubs) con rodamientos integrados para vehículos nacionales e importados. Componente esencial para el giro libre y seguro de las ruedas. Disponibles en configuraciones para eje delantero y trasero, con o sin sensor ABS.',
 'a6000000-0000-0000-0000-000000000006',
 'ruedas',
 10,
 '/images/products/cubo de rueda.webp',
 '{"Tipo":"Cubo de rueda con rodamiento integrado","Material":"Acero al carbono de alta resistencia","Rodamiento":"Doble hilera de bolas / rodillos cónicos","Sensor ABS":"Disponible con y sin sensor","Posición":"Delantero / Trasero","Marcas disponibles":"SKF, NSK, NTN, Timken"}',
 ARRAY['Vehículos particulares','Camionetas y SUV','Utilitarios','Vehículos comerciales livianos'],
 ARRAY['Rodamientos sellados de por vida','Alta capacidad de carga radial y axial','Compatibilidad con sistema ABS','Instalación directa (bolt-on)','Pre-engrasados de fábrica','Máxima seguridad en conducción'],
 'SKF / NSK / NTN',
 true);
